#!/usr/bin/env bash
# runner.sh — pluggable model runner for prompt-rail.
#
# Contract: JSON on stdin {"prompt","case","vars"} -> completion text on stdout.
# Print ONLY the completion to stdout; send anything else to stderr.
#
# You do NOT edit this file to switch models — it reads <workdir>/config.env
# and branches on RUNNER_PROVIDER. Copy config.template.env to config.env and
# edit that instead. See references/runners.md.
set -euo pipefail

here="$(cd "$(dirname "$0")" && pwd)"
cfg="${PROMPT_RAIL_CONFIG:-$here/config.env}"
if [[ -f "$cfg" ]]; then
  set -a; . "$cfg"; set +a
fi

provider="${RUNNER_PROVIDER:?set RUNNER_PROVIDER in config.env}"
temp="${RUNNER_TEMPERATURE:-0}"

payload=$(cat)
prompt=$(printf '%s' "$payload" | python3 -c 'import sys,json;print(json.load(sys.stdin)["prompt"])')

case "$provider" in

  openai_compatible)
    : "${RUNNER_BASE:?set RUNNER_BASE}"; : "${RUNNER_MODEL:?set RUNNER_MODEL}"
    : "${RUNNER_API_KEY_ENV:?set RUNNER_API_KEY_ENV (name of the key env var)}"
    key="${!RUNNER_API_KEY_ENV:?$RUNNER_API_KEY_ENV is not exported in your shell}"
    body=$(printf '%s' "$payload" | MODEL="$RUNNER_MODEL" TEMP="$temp" python3 -c '
import sys, json, os
prompt = json.load(sys.stdin)["prompt"]
print(json.dumps({
    "model": os.environ["MODEL"],
    "temperature": float(os.environ["TEMP"]),
    "messages": [{"role": "user", "content": prompt}],
}))')
    curl -sS "$RUNNER_BASE/chat/completions" \
      -H "Authorization: Bearer $key" \
      -H "Content-Type: application/json" \
      -d "$body" \
    | python3 -c 'import sys,json;print(json.load(sys.stdin)["choices"][0]["message"]["content"])'
    ;;

  claude_cli)
    # RUNNER_MODEL optional; blank = CLI default.
    if [[ -n "${RUNNER_MODEL:-}" ]]; then
      printf '%s' "$prompt" | claude -p --model "$RUNNER_MODEL" --output-format text
    else
      printf '%s' "$prompt" | claude -p --output-format text
    fi
    ;;

  *)
    echo "unknown RUNNER_PROVIDER: $provider" >&2
    exit 1
    ;;
esac
